# Generated by Django 5.2.12 on 2026-03-31 19:16

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_en', models.CharField(blank=True, default='', max_length=500, verbose_name='Title (English)')),
                ('body_no', wagtail.fields.RichTextField(blank=True, default='', verbose_name='Innhold (norsk)')),
                ('body_en', wagtail.fields.RichTextField(blank=True, default='', verbose_name='Content (English)')),
            ],
            options={
                'verbose_name': 'Innholdsside',
                'verbose_name_plural': 'Innholdssider',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Hjemmeside',
            },
            bases=('wagtailcore.page',),
        ),
    ]
