# Generated by Django 5.2.12 on 2026-04-01 00:13

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_en', models.CharField(blank=True, default='', max_length=500, verbose_name='Title (English)')),
                ('icon', models.CharField(blank=True, default='', help_text='Material Design icon name, e.g. mdi-calendar', max_length=50, verbose_name='Ikon (MDI)')),
                ('vue_route_name', models.CharField(help_text="Named route in Vue router, e.g. 'schedule'", max_length=100, verbose_name='Vue route name')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='Vis i meny')),
                ('menu_order', models.IntegerField(default=0, help_text='Lavere tall = vises først', verbose_name='Sortering i meny')),
            ],
            options={
                'verbose_name': 'Funksjonsside',
                'verbose_name_plural': 'Funksjonssider',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PricingPage',
            fields=[
                ('contentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.contentpage')),
            ],
            options={
                'verbose_name': 'Prisside',
                'verbose_name_plural': 'Prissider',
            },
            bases=('home.contentpage',),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Material Design icon name, e.g. mdi-information', max_length=50, verbose_name='Ikon (MDI)'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='menu_order',
            field=models.IntegerField(default=0, help_text='Lavere tall = vises først', verbose_name='Sortering i meny'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='show_in_menu',
            field=models.BooleanField(default=True, verbose_name='Vis i meny'),
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category_no', models.CharField(max_length=200, verbose_name='Kategori (norsk)')),
                ('category_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Category (English)')),
                ('price_nok', models.IntegerField(verbose_name='Pris (NOK)')),
                ('description_no', models.CharField(blank=True, default='', max_length=500, verbose_name='Beskrivelse (norsk)')),
                ('description_en', models.CharField(blank=True, default='', max_length=500, verbose_name='Description (English)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='home.pricingpage')),
            ],
            options={
                'verbose_name': 'Prislinje',
                'verbose_name_plural': 'Prislinjer',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
